/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PropertiesImport } from './routes/properties'
import { Route as PcsImport } from './routes/pcs'
import { Route as FabImport } from './routes/fab'
import { Route as DynamicImport } from './routes/dynamic'
import { Route as AccountImport } from './routes/account'
import { Route as EnqueteFormationExpertDashboardImport } from './routes/$enquete/formation/expert/dashboard'
import { Route as EnqueteFormationCodeurDashboardImport } from './routes/$enquete/formation/codeur/dashboard'
import { Route as EnqueteEmploiExpertDashboardImport } from './routes/$enquete/emploi/expert/dashboard'
import { Route as EnqueteEmploiCodeurDashboardImport } from './routes/$enquete/emploi/codeur/dashboard'
import { Route as EnqueteFormationExpertLogementLogementImport } from './routes/$enquete/formation/expert/logement/$logement'
import { Route as EnqueteFormationCodeurLogementLogementImport } from './routes/$enquete/formation/codeur/logement/$logement'
import { Route as EnqueteEmploiExpertLogementLogementImport } from './routes/$enquete/emploi/expert/logement/$logement'
import { Route as EnqueteEmploiCodeurLogementLogementImport } from './routes/$enquete/emploi/codeur/logement/$logement'
import { Route as EnqueteFormationExpertLogementLogementDetailsIndexImport } from './routes/$enquete/formation/expert/logement/$logementDetails/$index'
import { Route as EnqueteFormationCodeurLogementLogementDetailsIndexImport } from './routes/$enquete/formation/codeur/logement/$logementDetails/$index'
import { Route as EnqueteEmploiExpertLogementLogementDetailsIndexImport } from './routes/$enquete/emploi/expert/logement/$logementDetails/$index'
import { Route as EnqueteEmploiCodeurLogementLogementDetailsIndexImport } from './routes/$enquete/emploi/codeur/logement/$logementDetails/$index'

// Create Virtual Routes

const MuiLazyImport = createFileRoute('/mui')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MuiLazyRoute = MuiLazyImport.update({
  path: '/mui',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/mui.lazy').then((d) => d.Route))

const PropertiesRoute = PropertiesImport.update({
  path: '/properties',
  getParentRoute: () => rootRoute,
} as any)

const PcsRoute = PcsImport.update({
  path: '/pcs',
  getParentRoute: () => rootRoute,
} as any)

const FabRoute = FabImport.update({
  path: '/fab',
  getParentRoute: () => rootRoute,
} as any)

const DynamicRoute = DynamicImport.update({
  path: '/dynamic',
  getParentRoute: () => rootRoute,
} as any)

const AccountRoute = AccountImport.update({
  path: '/account',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const EnqueteFormationExpertDashboardRoute =
  EnqueteFormationExpertDashboardImport.update({
    path: '/$enquete/formation/expert/dashboard',
    getParentRoute: () => rootRoute,
  } as any)

const EnqueteFormationCodeurDashboardRoute =
  EnqueteFormationCodeurDashboardImport.update({
    path: '/$enquete/formation/codeur/dashboard',
    getParentRoute: () => rootRoute,
  } as any)

const EnqueteEmploiExpertDashboardRoute =
  EnqueteEmploiExpertDashboardImport.update({
    path: '/$enquete/emploi/expert/dashboard',
    getParentRoute: () => rootRoute,
  } as any)

const EnqueteEmploiCodeurDashboardRoute =
  EnqueteEmploiCodeurDashboardImport.update({
    path: '/$enquete/emploi/codeur/dashboard',
    getParentRoute: () => rootRoute,
  } as any)

const EnqueteFormationExpertLogementLogementRoute =
  EnqueteFormationExpertLogementLogementImport.update({
    path: '/$enquete/formation/expert/logement/$logement',
    getParentRoute: () => rootRoute,
  } as any)

const EnqueteFormationCodeurLogementLogementRoute =
  EnqueteFormationCodeurLogementLogementImport.update({
    path: '/$enquete/formation/codeur/logement/$logement',
    getParentRoute: () => rootRoute,
  } as any)

const EnqueteEmploiExpertLogementLogementRoute =
  EnqueteEmploiExpertLogementLogementImport.update({
    path: '/$enquete/emploi/expert/logement/$logement',
    getParentRoute: () => rootRoute,
  } as any)

const EnqueteEmploiCodeurLogementLogementRoute =
  EnqueteEmploiCodeurLogementLogementImport.update({
    path: '/$enquete/emploi/codeur/logement/$logement',
    getParentRoute: () => rootRoute,
  } as any)

const EnqueteFormationExpertLogementLogementDetailsIndexRoute =
  EnqueteFormationExpertLogementLogementDetailsIndexImport.update({
    path: '/$enquete/formation/expert/logement/$logementDetails/$index',
    getParentRoute: () => rootRoute,
  } as any)

const EnqueteFormationCodeurLogementLogementDetailsIndexRoute =
  EnqueteFormationCodeurLogementLogementDetailsIndexImport.update({
    path: '/$enquete/formation/codeur/logement/$logementDetails/$index',
    getParentRoute: () => rootRoute,
  } as any)

const EnqueteEmploiExpertLogementLogementDetailsIndexRoute =
  EnqueteEmploiExpertLogementLogementDetailsIndexImport.update({
    path: '/$enquete/emploi/expert/logement/$logementDetails/$index',
    getParentRoute: () => rootRoute,
  } as any)

const EnqueteEmploiCodeurLogementLogementDetailsIndexRoute =
  EnqueteEmploiCodeurLogementLogementDetailsIndexImport.update({
    path: '/$enquete/emploi/codeur/logement/$logementDetails/$index',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountImport
      parentRoute: typeof rootRoute
    }
    '/dynamic': {
      id: '/dynamic'
      path: '/dynamic'
      fullPath: '/dynamic'
      preLoaderRoute: typeof DynamicImport
      parentRoute: typeof rootRoute
    }
    '/fab': {
      id: '/fab'
      path: '/fab'
      fullPath: '/fab'
      preLoaderRoute: typeof FabImport
      parentRoute: typeof rootRoute
    }
    '/pcs': {
      id: '/pcs'
      path: '/pcs'
      fullPath: '/pcs'
      preLoaderRoute: typeof PcsImport
      parentRoute: typeof rootRoute
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesImport
      parentRoute: typeof rootRoute
    }
    '/mui': {
      id: '/mui'
      path: '/mui'
      fullPath: '/mui'
      preLoaderRoute: typeof MuiLazyImport
      parentRoute: typeof rootRoute
    }
    '/$enquete/emploi/codeur/dashboard': {
      id: '/$enquete/emploi/codeur/dashboard'
      path: '/$enquete/emploi/codeur/dashboard'
      fullPath: '/$enquete/emploi/codeur/dashboard'
      preLoaderRoute: typeof EnqueteEmploiCodeurDashboardImport
      parentRoute: typeof rootRoute
    }
    '/$enquete/emploi/expert/dashboard': {
      id: '/$enquete/emploi/expert/dashboard'
      path: '/$enquete/emploi/expert/dashboard'
      fullPath: '/$enquete/emploi/expert/dashboard'
      preLoaderRoute: typeof EnqueteEmploiExpertDashboardImport
      parentRoute: typeof rootRoute
    }
    '/$enquete/formation/codeur/dashboard': {
      id: '/$enquete/formation/codeur/dashboard'
      path: '/$enquete/formation/codeur/dashboard'
      fullPath: '/$enquete/formation/codeur/dashboard'
      preLoaderRoute: typeof EnqueteFormationCodeurDashboardImport
      parentRoute: typeof rootRoute
    }
    '/$enquete/formation/expert/dashboard': {
      id: '/$enquete/formation/expert/dashboard'
      path: '/$enquete/formation/expert/dashboard'
      fullPath: '/$enquete/formation/expert/dashboard'
      preLoaderRoute: typeof EnqueteFormationExpertDashboardImport
      parentRoute: typeof rootRoute
    }
    '/$enquete/emploi/codeur/logement/$logement': {
      id: '/$enquete/emploi/codeur/logement/$logement'
      path: '/$enquete/emploi/codeur/logement/$logement'
      fullPath: '/$enquete/emploi/codeur/logement/$logement'
      preLoaderRoute: typeof EnqueteEmploiCodeurLogementLogementImport
      parentRoute: typeof rootRoute
    }
    '/$enquete/emploi/expert/logement/$logement': {
      id: '/$enquete/emploi/expert/logement/$logement'
      path: '/$enquete/emploi/expert/logement/$logement'
      fullPath: '/$enquete/emploi/expert/logement/$logement'
      preLoaderRoute: typeof EnqueteEmploiExpertLogementLogementImport
      parentRoute: typeof rootRoute
    }
    '/$enquete/formation/codeur/logement/$logement': {
      id: '/$enquete/formation/codeur/logement/$logement'
      path: '/$enquete/formation/codeur/logement/$logement'
      fullPath: '/$enquete/formation/codeur/logement/$logement'
      preLoaderRoute: typeof EnqueteFormationCodeurLogementLogementImport
      parentRoute: typeof rootRoute
    }
    '/$enquete/formation/expert/logement/$logement': {
      id: '/$enquete/formation/expert/logement/$logement'
      path: '/$enquete/formation/expert/logement/$logement'
      fullPath: '/$enquete/formation/expert/logement/$logement'
      preLoaderRoute: typeof EnqueteFormationExpertLogementLogementImport
      parentRoute: typeof rootRoute
    }
    '/$enquete/emploi/codeur/logement/$logementDetails/$index': {
      id: '/$enquete/emploi/codeur/logement/$logementDetails/$index'
      path: '/$enquete/emploi/codeur/logement/$logementDetails/$index'
      fullPath: '/$enquete/emploi/codeur/logement/$logementDetails/$index'
      preLoaderRoute: typeof EnqueteEmploiCodeurLogementLogementDetailsIndexImport
      parentRoute: typeof rootRoute
    }
    '/$enquete/emploi/expert/logement/$logementDetails/$index': {
      id: '/$enquete/emploi/expert/logement/$logementDetails/$index'
      path: '/$enquete/emploi/expert/logement/$logementDetails/$index'
      fullPath: '/$enquete/emploi/expert/logement/$logementDetails/$index'
      preLoaderRoute: typeof EnqueteEmploiExpertLogementLogementDetailsIndexImport
      parentRoute: typeof rootRoute
    }
    '/$enquete/formation/codeur/logement/$logementDetails/$index': {
      id: '/$enquete/formation/codeur/logement/$logementDetails/$index'
      path: '/$enquete/formation/codeur/logement/$logementDetails/$index'
      fullPath: '/$enquete/formation/codeur/logement/$logementDetails/$index'
      preLoaderRoute: typeof EnqueteFormationCodeurLogementLogementDetailsIndexImport
      parentRoute: typeof rootRoute
    }
    '/$enquete/formation/expert/logement/$logementDetails/$index': {
      id: '/$enquete/formation/expert/logement/$logementDetails/$index'
      path: '/$enquete/formation/expert/logement/$logementDetails/$index'
      fullPath: '/$enquete/formation/expert/logement/$logementDetails/$index'
      preLoaderRoute: typeof EnqueteFormationExpertLogementLogementDetailsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AccountRoute,
  DynamicRoute,
  FabRoute,
  PcsRoute,
  PropertiesRoute,
  MuiLazyRoute,
  EnqueteEmploiCodeurDashboardRoute,
  EnqueteEmploiExpertDashboardRoute,
  EnqueteFormationCodeurDashboardRoute,
  EnqueteFormationExpertDashboardRoute,
  EnqueteEmploiCodeurLogementLogementRoute,
  EnqueteEmploiExpertLogementLogementRoute,
  EnqueteFormationCodeurLogementLogementRoute,
  EnqueteFormationExpertLogementLogementRoute,
  EnqueteEmploiCodeurLogementLogementDetailsIndexRoute,
  EnqueteEmploiExpertLogementLogementDetailsIndexRoute,
  EnqueteFormationCodeurLogementLogementDetailsIndexRoute,
  EnqueteFormationExpertLogementLogementDetailsIndexRoute,
})

/* prettier-ignore-end */
